export const fill = {
  'on-bg': {
    // Orbit Styleguide
    default: 'var(--icon-on-bg-default-default)',
    accent: 'var(--icon-on-bg-default-accent)',
    subtle: 'var(--icon-on-bg-default-subtle)',
    info: 'var(--icon-on-bg-feedback-info)',
    'info-inverse': 'var(--icon-on-bg-feedback-info-inverse)',
    success: 'var(--icon-on-bg-feedback-success)',
    'success-inverse': 'var(--icon-on-bg-feedback-success-inverse)',
    warning: 'var(--icon-on-bg-feedback-warning)',
    'warning-inverse': 'var(--icon-on-bg-feedback-warning-inverse)',
    error: 'var(--icon-on-bg-feedback-error)',
    'error-inverse': 'var(--icon-on-bg-feedback-error-inverse)',
    1: 'var(--icon-on-bg-container-01)',
    '1-accent': 'var(--icon-on-bg-container-01-accent)',
    2: 'var(--icon-on-bg-container-02)',
    '2-accent': 'var(--icon-on-bg-container-02-accent)',
    3: 'var(--icon-on-bg-container-03)',
    '3-accent': 'var(--icon-on-bg-container-03-accent)',
    4: 'var(--icon-on-bg-container-04)',
    '4-accent': 'var(--icon-on-bg-container-04-accent)',
    // Orbit Design Kit
    'primary-disabled': 'var(--icon-on-bg-primary-disabled)',
    'primary-focus': 'var(--icon-on-bg-primary-focus)',
    'primary-hover': 'var(--icon-on-bg-primary-hover)',
    'primary-idle': 'var(--icon-on-bg-primary-idle)',
    'primary-pressed': 'var(--icon-on-bg-primary-pressed)',
    'secondary-disabled': 'var(--icon-on-bg-secondary-disabled)',
    'secondary-focus': 'var(--icon-on-bg-secondary-focus)',
    'secondary-hover': 'var(--icon-on-bg-secondary-hover)',
    'secondary-idle': 'var(--icon-on-bg-secondary-idle)',
    'secondary-pressed': 'var(--icon-on-bg-secondary-pressed)',
    'tertiary-disabled': 'var(--icon-on-bg-tertiary-disabled)',
    'tertiary-focus': 'var(--icon-on-bg-tertiary-focus)',
    'tertiary-hover': 'var(--icon-on-bg-tertiary-hover)',
    'tertiary-idle': 'var(--icon-on-bg-tertiary-idle)',
    'tertiary-pressed': 'var(--icon-on-bg-tertiary-pressed)',
    'trigger-active': 'var(--icon-on-bg-trigger-active)',
    'trigger-active-variant': 'var(--icon-on-bg-trigger-active-variant)',
    'trigger-disabled': 'var(--icon-on-bg-trigger-disabled)',
    'trigger-focus': 'var(--icon-on-bg-trigger-focus)',
    'trigger-hover': 'var(--icon-on-bg-trigger-hover)',
    'trigger-idle': 'var(--icon-on-bg-trigger-idle)',
    'trigger-idle-variant': 'var(--icon-on-bg-trigger-idle-variant)',
    'trigger-pressed': 'var(--icon-on-bg-trigger-pressed)',
  },
} as const;
