export const textColors = {
  'on-bg': {
    // Orbit Styleguide
    default: 'var(--text-on-bg-default-default)',
    accent: 'var(--text-on-bg-default-accent)',
    'large-text': 'var(--text-on-bg-default-large-text)',
    subtle: 'var(--text-on-bg-default-subtle)',
    'link-idle': 'var(--text-on-bg-default-link-idle)',
    'link-hover': 'var(--text-on-bg-default-link-hover)',
    'link-pressed': 'var(--text-on-bg-default-link-pressed)',
    1: 'var(--text-on-bg-container-01)',
    '1-accent': 'var(--text-on-bg-container-01-accent)',
    2: 'var(--text-on-bg-container-02)',
    '2-accent': 'var(--text-on-bg-container-02-accent)',
    3: 'var(--text-on-bg-container-03)',
    '3-accent': 'var(--text-on-bg-container-03-accent)',
    '3-subtle': 'var(--text-on-bg-container-03-subtle)',
    4: 'var(--text-on-bg-container-04)',
    '4-accent': 'var(--text-on-bg-container-04-accent)',
    error: 'var(--text-on-bg-feedback-error)',
    'error-inverse': 'var(--text-on-bg-feedback-error-inverse)',
    'error-inverse-accent': 'var(--text-on-bg-feedback-error-inverse-accent)',
    info: 'var(--text-on-bg-feedback-info)',
    'info-inverse': 'var(--text-on-bg-feedback-info-inverse)',
    'info-inverse-accent': 'var(--text-on-bg-feedback-info-inverse-accent)',
    success: 'var(--text-on-bg-feedback-success)',
    'success-inverse': 'var(--text-on-bg-feedback-success-inverse)',
    'success-inverse-accent':
      'var(--text-on-bg-feedback-success-inverse-accent)',
    warning: 'var(--text-on-bg-feedback-warning)',
    'warning-inverse': 'var(--text-on-bg-feedback-warning-inverse)',
    'warning-inverse-accent':
      'var(--text-on-bg-feedback-warning-inverse-accent)',
    // Orbit Design Kit
    primary: {
      idle: 'var(--on-bg-primary-idle)',
      hover: 'var(--on-bg-primary-hover)',
      pressed: 'var(--on-bg-primary-pressed)',
      focus: 'var(--on-bg-primary-focus)',
      disabled: 'var(--on-bg-primary-disabled)',
    },
    secondary: {
      idle: 'var(--on-bg-secondary-idle)',
      hover: 'var(--on-bg-secondary-hover)',
      pressed: 'var(--on-bg-secondary-pressed)',
      focus: 'var(--on-bg-secondary-focus)',
      disabled: 'var(--on-bg-secondary-disabled)',
    },
    tertiary: {
      idle: 'var(--on-bg-tertiary-idle)',
      hover: 'var(--on-bg-tertiary-hover)',
      pressed: 'var(--on-bg-tertiary-pressed)',
      focus: 'var(--on-bg-tertiary-focus)',
      disabled: 'var(--on-bg-tertiary-disabled)',
    },
    trigger: {
      idle: 'var(--on-bg-trigger-idle)',
      'idle-variant': 'var(--on-bg-trigger-idle)',
      hover: 'var(--on-bg-trigger-hover)',
      pressed: 'var(--on-bg-trigger-pressed)',
      active: 'var(--on-bg-trigger-active)',
      'active-variant': 'var(--on-bg-trigger-active-variant)',
      focus: 'var(--on-bg-trigger-focus)',
      disabled: 'var(--on-bg-trigger-disabled)',
    },
  },
} as const;
